spring:
  application:
    name: zuul
  rabbitmq:
    host: 192.168.32.128
    port: 5672
    username: admin
    password: admin    
server:
  port: 3001
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka

zuul:
  retryable: true

#m默认从注册中心远程调用
#  routes:
#    item-service: /item-service/**
#    user-service: /user-service/**
#    order-service: /order-service/**
       
ribbon: #可以不配有默认值
  ConnectTimeout: 1000
  ReadTimeout: 1000
  MaxAutoRetriesNextServer: 1
  MaxAutoRetries: 1    

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 200

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream 
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh                       